### ISSUE TITLE
Add table microsoft365_defender

### ISSUE THREAD

**Issue by ukbrucetaylor** [turbot/steampipe-plugin-microsoft365#8]
Please consider adding defender data to the 365 plugin.  https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/exposed-apis-list?view=o365-worldwide

It would be extermely useful to Steampipe to query and produce a list of all our laptops vulneraiblity status.

**Comment by misraved** [comment]
Welcome to Steampipe @ukbrucetaylor 👍 and thanks for opening this issue 😃 .

Agreed, the addition of this table would be extremely useful 👍.

I tried to look for the corresponding APIs in https://pkg.go.dev/github.com/microsoftgraph/msgraph-sdk-go SDK but without much success. I don't think the SDK has added support for retrieving the defender incidents (https://learn.microsoft.com/en-us/microsoft-365/security/defender/api-incident?view=o365-worldwide#methods) as of now.
